/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.digital.innovation.one.avancado;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
